### ISSUE TITLE
FYIC 2023 Discord Bot

### ISSUE THREAD

**Issue by danielljeon** [EZCampusDevs/discord_bot#1]
# Project Scope for FYIC 2023 Conference

1. Conference attendees are verified using pre-made EZC user accounts
   - Verify attendees using our fastapi user auth endpoint
   - Upon successful auth, change the attendee's Discord server nickname to the pre-made user display name
   - Give the attendee a "verified" role on the Discord server to get access to all conference channels

**Comment by Minnowo** [comment]
Part A and C are done. The bot tries to change the nickname, but doesn't have permission for some reason. I'm not really sure if it's a Discord perms thing or a bot perms thing though

**Comment by Minnowo** [comment]
This is fixed since the bot was given more permissions.
